# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: humanstrategoweb-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humanstrategoweb
  template:
    metadata:
      labels:
        app: humanstrategoweb
    spec:
      containers:
        - name: humanstrategoweb-app
          image: us-central1-docker.pkg.dev/human-stratego-web/human-stratego-web-artifacts/humanstrategoweb-gke:latest
          # This app listens on port 8080 for web traffic by default.
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
